### ISSUE TITLE
Integration doesn't show up in Add Integration menu

### ISSUE THREAD

**Issue by kooijman599** [DeebotUniverse/Deebot-4-Home-Assistant#428] opened 2023-09-25 07:42 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

![Screenshot_2023-09-25-09-32-29-862_io homeassistant companion android](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/145869596/0d360fc0-b200-4bb5-afd2-8211e0cc70d0)

I downloaded the integration in HACS. Then I restarted the HA system and move over to Settings to add the integration. However, Deebot doesn't show up there.

### On which deebot vacuum you have the issue?

Deebot 900

### Which version of the Deebot component are you using?

2.1.0

### Which version of Home Assistant are you using?

2023.9.2

### What type of installation are you running?

Home Assistant OS

### Country

nl

### Continent

eu

### Instance type

Cloud

**Comment by edenhaus** [comment] 2023-09-25 07:59
Duplicate of #426

**Closed as not planned by edenhaus** 2023-09-25 07:59 UTC
Labels: bug
