### ISSUE TITLE
last_cleaning sensor not working (X1 Omni)

### ISSUE THREAD

**Issue by stevehop** [DeebotUniverse/Deebot-4-Home-Assistant#183] opened 2022-05-25 10:29 UTC
Probably related to the fact that no event seems to be fired at start or end of cleaning. Have tried listening to **CleanLogEvent** and **deebot_cleaning_job** but not seeing anything.

Deebot related log entries:

```
2022-05-25 10:14:19 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.deebot
2022-05-25 10:14:19 INFO (MainThread) [homeassistant.components.button] Setting up button.deebot
2022-05-25 10:14:19 INFO (MainThread) [homeassistant.components.camera] Setting up camera.deebot
2022-05-25 10:14:19 INFO (MainThread) [homeassistant.components.number] Setting up number.deebot
2022-05-25 10:14:19 INFO (MainThread) [homeassistant.components.select] Setting up select.deebot
2022-05-25 10:14:19 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.deebot
2022-05-25 10:14:19 INFO (MainThread) [homeassistant.components.switch] Setting up switch.deebot
2022-05-25 10:14:19 INFO (MainThread) [homeassistant.components.vacuum] Setting up vacuum.deebot
2022-05-25 10:28:24 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'vw', 'mid': '1426527509'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
KeyError: 'subsets'
2022-05-25 10:28:24 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'vw', 'mid': '1426527509'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
KeyError: 'subsets'
2022-05-25 10:28:24 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'ar', 'mid': '1567673174'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
KeyError: 'subsets'
2022-05-25 10:28:24 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'vw', 'mid': '1567673174'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
KeyError: 'subsets'
2022-05-25 10:28:24 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'vw', 'mid': '1567673174'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
2022-05-25 10:32:30 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'ar', 'mid': '1567673174'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
2022-05-25 11:12:40 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'vw', 'mid': '1103622091'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
KeyError: 'subsets'
2022-05-25 11:12:40 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'ar', 'mid': '268145692'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
KeyError: 'subsets'
2022-05-25 11:12:40 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'vw', 'mid': '268145692'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
KeyError: 'subsets'
2022-05-25 11:12:40 WARNING (MainThread) [deebot_client.message] Could not parse getMapSet: {'type': 'vw', 'mid': '268145692'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 52, in wrapper
    response = func(cls, event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 108, in __handle_body_data
    return cls._handle_body_data(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/message.py", line 97, in _handle_body_data
    return cls._handle_body_data_dict(event_bus, data)
  File "/usr/local/lib/python3.9/site-packages/deebot_client/commands/map.py", line 124, in _handle_body_data_dict
    subsets = [subset["mssid"] for subset in data["subsets"]]
KeyError: 'subsets'
```

**Comment by edenhaus** [comment] 2022-05-26 12:41
Please open next time the issue directly in the repo of the integration as the docs are used across multiple projects.

**Comment by edenhaus** [comment] 2022-05-26 12:47
I need debug logs to find out, what is different in your response.
Please refer to https://deebot.readthedocs.io/integrations/home-assistant/issues/, how you can activate debug logs.

**Comment by stevehop** [comment] 2022-05-26 12:51
> Please open next time the issue directly in the repo of the integration as the docs are used across multiple projects.

Apologies, thought I'd raised in the main repo, will debug and report back

**Comment by stevehop** [comment] 2022-05-26 13:27
[deebot_debug.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/8779295/deebot_debug.txt)

Debug log attached

**Comment by edenhaus** [comment] 2022-05-28 19:40
@stevehop I cannot find the above exception in your debug logs.
Can you please attach the logs, where the issue happens :)

**Comment by stevehop** [comment] 2022-06-03 11:00
@edenhaus I believe that my problem is a duplicate of https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/166 

I have attached new debug logs based on v1.3.2

It finished cleaning at 08.37 on 3rd of June but didn't update the last_cleaning sensor

[deebot_debug.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/8831817/deebot_debug.txt)

**Comment by edenhaus** [comment] 2022-06-27 16:34
Duplicate of #166 
I have commented there my findings.

**Closed as not planned by edenhaus** 2022-06-27 16:34 UTC
