### ISSUE TITLE
Deebot N8+ not updating status

### ISSUE THREAD

**Issue by seawiid** [DeebotUniverse/Deebot-4-Home-Assistant#346] opened 2023-05-07 10:06 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

I'm not sure when this started, but although previously this integration is working fine, lately my deebot is not updating status when vacuuming, returning, or docked. if i use the command deebot.refresh then i can get the current status but it is severely  limiting automations at the moment

### Diagnostics information

[deebot-336b5e44d09e4498474770d6c7390f96-Deebot-ba09a4596480bf3adad5185770b789d8.json.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11414584/deebot-336b5e44d09e4498474770d6c7390f96-Deebot-ba09a4596480bf3adad5185770b789d8.json.txt)

### Anything in the logs that might be useful for us?

```txt
I am sometimes getting this error on various commands:
Command "clean" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

### Additional information

seems to be quite a delay between triggering commands to deebot and when it responds. sometimes commands aren't going through. wifi connection is fine, and app is working.

**Comment by edenhaus** [comment] 2023-05-08 08:51
> ```
> Command "clean" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
> ```

This means that your bot was not answering in time for the given command. In other words your bot has network problems. Can you please verify that it has a stable internet connection. Without internet connection you don't get any information about it. I assume you have changed (probably without notice) your wlan coverage

**Comment by seawiid** [comment] 2023-05-10 10:48
nope. no change to wlan. internet is fine and very stable. it also doesn't give this error all the time which is weird. I do notice the deebot is 'sticky' to one access point and doesn't like to roam. i haven't quite figured out why yet.

however, the not updating issue seems to be separate as commands are coming through to the robot at times but it is not updating status in home assistant (when cleaning for instance)

**Comment by edenhaus** [comment] 2023-05-11 19:46
Than this issue is a duplicate of #293

**Closed as not planned by edenhaus** 2023-05-11 19:46 UTC
Labels: bug, need-more-information
