### ISSUE TITLE
Warning at startup: Command "getMapSubSet" was not successfully

### ISSUE THREAD

**Issue by StefanoGiugliano** [DeebotUniverse/Deebot-4-Home-Assistant#366] opened 2023-06-09 05:45 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Warning at startup:
Command "getMapSubSet" was not successfully

### Diagnostics information

Home Assistant 2023.6.0
Deebot 4 Home Assistant: This is happening both with 1.5.0 and with 1.6.0. I had to downgrade from 1.6.0 to 1.5.0 because of the other bug I opened.

### Anything in the logs that might be useful for us?

```txt
2023-06-08 16:01:50.987 WARNING (MainThread) [deebot_client.commands.common] Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2023-06-08 16:01:51.020 WARNING (MainThread) [deebot_client.commands.common] Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2023-06-08 16:01:52.824 WARNING (MainThread) [deebot_client.commands.common] Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

### Additional information

[deebot.txt](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/files/11702655/deebot.txt)

**Comment by edenhaus** [comment] 2023-06-09 21:57
This warning means that either the bot has network/connections issues or it doesn‘t support the command. Can you please check that your bot has a stable network/internet connection.
 Are you getting the same warning for other commands?

**Comment by StefanoGiugliano** [comment] 2023-06-10 05:38
The bot has a stable connection and I can use ir properly with the Ecovacs app. I am not getting any other command warning in the log, just this at the start up. Btw, the live camera map is not clear, it's something a bit weird...

The X1 Omni has a better map image on the app... maybe there's something different here in API integration?

![Map](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/129314675/4bdaf748-f0ec-4664-886d-976d100b67f4)

**Comment by edenhaus** [comment] 2023-06-10 21:08
Duplicate of #268

**Closed as not planned by edenhaus** 2023-06-10 21:08 UTC
Labels: bug, need-more-information
