### ISSUE TITLE
Support T8MAX?

### ISSUE THREAD

**Issue by qw8881569** [DeebotUniverse/Deebot-4-Home-Assistant#208] opened 2022-07-07 03:09 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

After logging in, I don't see the mission device, may I ask if T8 MAX is not supported?

### On which deebot vacuum you have the issue?

地宝 T8 MAX

### Which version of the Deebot component are you using?

1.3.1

### Which version of Home Assistant are you using?

2022.6.7

### What type of installation are you running?

Home Assistant Container

### Country

中国

### Continent

ww

**Comment by edenhaus** [comment] 2022-07-07 05:40
Duplicate of #91

**Closed as not planned by edenhaus** 2022-07-07 05:40 UTC
Labels: question
