### ISSUE TITLE
Error on adding Ozmo 950 - User input malformed

### ISSUE THREAD

**Issue by greilflorian** [DeebotUniverse/Deebot-4-Home-Assistant#419] opened 2023-09-10 18:39 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

After installing and adding logging credentials I can tick my Ozmo 950 to integrate in HA.
Then I click confirm to finish config and I get the error message `User Input malformed: Value should be a list for dictionary value @ data['devices']`

### On which deebot vacuum you have the issue?

Deebot Ozmo 950

### Which version of the Deebot component are you using?

2.0.0

### Which version of Home Assistant are you using?

2023.9.1

### What type of installation are you running?

Home Assistant OS

### Country

De

### Continent

Eu

### Instance type

None

**Comment by kventil** [comment] 2023-09-11 06:04
Same problem here when trying to add my X1 Omni Pro

Home Assistant `2023.9.1`
Supervisor `2023.08.3` 
Operating System `10.5` 
Frontend `20230908.0 - latest` 
Deebot 4 Home Assistant `2.0.0`

Instance Type: `cloud`
Country: `de`
Continent: `eu`/`ww`


<img width="570" alt="image" src="https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/111546/612407b9-8bca-40fb-b75e-5500aff68d4d">

**Comment by kventil** [comment] 2023-09-11 06:15
I fiddled a bit with the POST request, when changing the request from:  `{"devices":"<robo-id>"}` to `{"devices":["<robo-id>"]}` it seeems to work.

(-> `http://homeassistant.local:8123/api/config/config_entries/flow/d8548dc924c729eec469995fffc4456f`)

**Comment by edenhaus** [comment] 2023-09-11 07:05
Duplicate of #415 and #417
Bug exists in the frontend

**Closed as not planned by edenhaus** 2023-09-11 07:05 UTC
Labels: bug
