### ISSUE TITLE
Support Goat G1

### ISSUE THREAD

**Issue by JeedHome44** [DeebotUniverse/Deebot-4-Home-Assistant#381] opened 2023-07-15 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Is your feature request related to a problem?

I just configured my Goat G1.
I tested to add it with this Integration and it’s appear

### Suggested solution

I don’t know coding but if I can help you with my Goat G1 !
![IMG_0205](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/41892950/e66604be-0549-4ca7-9b4f-7a2fc32c98cb)

**Comment by edenhaus** [comment] 2023-07-15 21:57
Duplicate of #341

**Closed as not planned by edenhaus** 2023-07-15 21:57 UTC
Labels: enhancement
