### ISSUE TITLE
Full support for Deebot T10 OMNI

### ISSUE THREAD

**Issue by VectorZhao** [DeebotUniverse/Deebot-4-Home-Assistant#475] opened 2023-12-08 06:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my feature request or idea

### Is your feature request related to a problem?

No response

### Suggested solution

No response

### Api example request

```txt
No response
```

### Alternatives you've considered

No response

### Additional information

Currently, T10 OMNI can be successfully added to HA, but the `map` instance is not available.

**Comment by edenhaus** [comment] 2023-12-13 11:15
Duplicate of #268

**Closed as not planned by edenhaus** 2023-12-13 11:15 UTC
Labels: enhancement
