### ISSUE TITLE
Command "getTotalStats" was not successfully: {'ret': 'fail', 'errno': 4200}

### ISSUE THREAD

**Issue by johnreind** [DeebotUniverse/Deebot-4-Home-Assistant#301] opened 2023-02-07 14:22 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Good morning,
recently I see in the logs of Home Assistant this error:

```
Logger: deebot_client.commands.common
Source: runner.py:128
First occurred: 6 feb 2023 11:31:57 (3 occurrences)
Last logged: 13:38:27

Command "getTotalStats" was not successfully: {'ret': 'fail', 'errno': 4200}
```

I have installed 

```
Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

```
Could someone know what is it and how fix it ??

Thanks

### Diagnostics information

Not necessary

**Comment by edenhaus** [comment] 2023-02-08 15:33
Duplicate of #293

**Closed as not planned by edenhaus** 2023-02-08 15:33 UTC
Labels: bug
