### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by gmaclean1981** [DeebotUniverse/Deebot-4-Home-Assistant#420] opened 2023-09-11 20:48 UTC
### Question

Hello!  Possibly something I've done incorrectly, but I'm having some difficulty getting Deebot configured.

Previously I had this setup through a VM of Home Assistant and it worked flawlessly.  Now I'm attempting to set up on a new install of a Docker HA, but getting this error when configuring:

User input malformed:  Value should be a list for dictionary value @ data['devices']

This comes on the screen immediately following inputting credentials and attempting to click 'submit'
![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/80365941/d4193faa-d25d-4004-8577-72be7190d84a)

**Comment by MLQ-BA** [comment] 2023-09-12 01:23
same error for me, Home Assistant 2023.9.1

Device name "Debbie", Deebot X1 Omni
No special characters in password

**Comment by edenhaus** [comment] 2023-09-12 07:16
Duplicate of #419 #415 #417
The bug exists in the frontend and will be fixed with the next patch release

**Closed as not planned** 2023-09-12 07:16 UTC
Labels: question
