### ISSUE TITLE
Waring at startup: Command "getMapSubSet" was not successfully

### ISSUE THREAD

**Issue by StefanoGiugliano** [DeebotUniverse/Deebot-4-Home-Assistant#365] opened 2023-06-08 14:04 UTC
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed the latest version

### The problem

Warning at startup:
Command "getMapSubSet" was not successfully

### Diagnostics information

Home Assistant 2023.6.0
Deebot 4 Home Assistant: 1.5.0 or 1.6.0

### Anything in the logs that might be useful for us?

```txt
2023-06-08 16:01:50.987 WARNING (MainThread) [deebot_client.commands.common] Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2023-06-08 16:01:51.020 WARNING (MainThread) [deebot_client.commands.common] Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2023-06-08 16:01:52.824 WARNING (MainThread) [deebot_client.commands.common] Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

**Comment by edenhaus** [comment] 2023-06-08 18:04
As written on your other issue I need the diagnostic information.

> Deebot 4 Home Assistant: 1.5.0 or 1.6.0

Please take your time to fill out the issue template with care. It's a big difference if you are using version `1.5.0` or `1.6.0`
I cannot help you if I don't get all information's to reproduce the issue.

> ```
> 2023-06-08 16:01:50.987 WARNING (MainThread) [deebot_client.commands.common] Command "getMapSubSet" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
> ```

Looks like Version `1.5.0` but than you cannot check the checkbock "I have installed the latest version".
Closing it for now. If the issue still persists, please create a new issue with all required information

**Closed as not planned by edenhaus** 2023-06-08 18:04 UTC
Labels: invalid

**Comment by StefanoGiugliano** [comment] 2023-06-09 05:35
This is happening both with version 1.5.0 and with version 1.6.0... why are you closing it instead of waiting for a feedback?
