### ISSUE TITLE
OZMO 930 PRO support?

### ISSUE THREAD

**Issue by lollo78** [DeebotUniverse/Deebot-4-Home-Assistant#514] opened 2024-01-28 20:30 UTC
### Question

Hi devs, 
I'm a little bit confused about all the ecovacs integrations for Home Assistant found in Google.
 
For what I've read, the "Home Assistant integration for deebot vacuums" is the killer ones, but I still haven't figured out if my "Ozmo 930 Pro" is supported or not.

Thanks for all your hard work!

**Comment by edenhaus** [comment] 2024-01-29 16:54
No this model is currently not supported by this integration

**Comment by lollo78** [comment] 2024-01-30 11:37
Thanks, 
there is an ETA for it?

**Comment by edenhaus** [comment] 2024-01-30 15:06
Nope, as the hole integration was reversed engineered as Ecovacs is not providing any information.
As I don't have your model, I can't help you. You need to analyze the traffic and add the missing parts with a PR :)
The community will say thank you if you do it :)

**Comment by edenhaus** [comment] 2024-02-01 18:45
Duplicate of https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/issues/467

**Closed as not planned by edenhaus** 2024-02-01 18:45 UTC
Labels: question

**Comment by kinower** [comment] 2024-03-22 09:45
hello,
my home asistant recognises my ozmo 930, it recognises that it is cleaning and the battery, but it does not react to the hoover's commands, I cannot start it or send it to the base.
When I give it a command I get: Service vacuum.turn_on not found.
